apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-eg6g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-eg6g
    app.kubernetes.io/part-of: cin4s-839-0063-app
  name: devfile-sample-eg6g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-eg6g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-eg6g
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0063-tenant/cin4s-839-0063-app/devfile-sample-eg6g@sha256:d2808451cd69dee433b27afec458727003b1147e959a5055c13ebe5645c92a87
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
